// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package registry

import (
	"github.com/lovung/GoCleanArchitecture/app/internal/interface/persistence/rdbms/gormrepo"
	"github.com/lovung/GoCleanArchitecture/app/internal/interface/restful/handler"
	"github.com/lovung/GoCleanArchitecture/app/internal/interface/restful/middleware"
	"github.com/lovung/GoCleanArchitecture/app/internal/usecase/interactor"
	"github.com/lovung/GoCleanArchitecture/pkg/gormer"
)

// Injectors from wire.go:

// TransactionMiddleware DI for middleware
func TransactionMiddleware() middleware.TransactionMiddleware {
	db := gormer.GetDB()
	txnDataSQL := gormrepo.NewTxnDataSQL(db)
	transactionMiddleware := middleware.NewTransactionMiddleware(txnDataSQL)
	return transactionMiddleware
}

// AuthHandler DI for handler
func AuthHandler() handler.AuthHandler {
	userRepository := gormrepo.NewUserRepository()
	userUseCase := interactor.NewUserUseCase(userRepository)
	authHandler := handler.NewAuthHandler(userUseCase)
	return authHandler
}
