// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package registry

import (
	"context"
	"github.com/lovung/GoCleanArchitecture/app/interface/persistence/rdbms/gorm"
	"github.com/lovung/GoCleanArchitecture/app/usecase"
	"github.com/lovung/GoCleanArchitecture/app/usecase/interactor"
	"github.com/lovung/GoCleanArchitecture/pkg/gormutil"
)

// Injectors from wire.go:

// InitializeSampleUseCase DI for use case
func InitializeSampleUseCase(ctx context.Context) usecase.SampleUseCase {
	db := gormutil.GetDB()
	sampleRepository := gorm.NewSampleRepository(ctx, db)
	sampleUseCase := interactor.NewSampleUseCase(ctx, sampleRepository)
	return sampleUseCase
}
