name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      TEST_RESULTS: /tmp/test-results
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Install tools
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0
        make install-devtools

    - name: Lint
      run: make lint

    - name: Test and Report
      run: make test && bash <(curl -s https://codecov.io/bash) -f $TEST_RESULTS/.testCoverage.txt -C $GITHUB_SHA -F unittests

    - name: Build
      run: make build 
